### PR TITLE
Ignore production config file, Add sample file

### PR DESCRIPTION
**Pull request by WesCossick**
Servers that auto pull the latest changes from GitHub are currently forced to overwrite the actual `config.php` file and any changes that have been made to it. This isn't the best setup, so I've renamed the file to `config.sample.php` and have added the `config.php` file to the `.gitignore` file.

### CODE REVIEW

**Comment by drAlberT** [comment]
It can be useful to have just to pull this repo to have a working app.. 

So, why don't implement something as this:
- distribute only `config.php.dist`
- check if `config.php` exists
 - yes: include it
 - no: use `config.php.dist` as a fallback  

What do you think? This should solve your problem, maintaining initial behavior

**Comment by WesCossick** [comment]
The behavior I've implemented is the industry standard. For reference, see [phpMyAdmin](https://github.com/phpmyadmin/phpmyadmin), where this repository gets its name.

**Comment by drAlberT** [comment]
As the majority of ppl having to manipulate DBs, I know very well `PMA` .. It was **the** mysql web interface for a very long time .. I think [Adminer](https://www.adminer.org/) can be a very good alternative nowadays, but this isn't the point now :)
It is my humble opinion that PMA is going to be quite "old" in its conception, very over-structured .. 

Apart this preamble, the fact that a famous SW is using a technique does not make the technique itself "_an industri standard_"  .. moreover, if a better solution can be implemented, even if the "old" solution is already good and cool, I think it should be taken into account.
SW should always be improved - programming evolves, tools such as composer are invented and became "industry standard" - and we all should think to solutions making our products more easy, more portable, simpler to integrate and so on ..

That said .. it's your project . Make your decision guy :)

**Comment by sasanrose** [comment]
Hey guys, I am truly sorry for a such a delay in response and I apologise for abandoning this project for quite a long time. Anyway, in this case I agree with @drAlberT at this point. This can be more backward compatible and as @drAlberT mentioned `It can be useful to have just to pull this repo to have a working app..`. However, I believe this project is seriously outdated from a design and technology stack point of view and needs a rewrite from scratch anyway.

Anyhow, for now I implemented what suggested by @drAlberT in 46c11309129accd78de6f168ef1eb15a1c5fd7df

**Comment by drAlberT** [comment]
Hi @sasanrose,
  good to know, but please take a look at #78

**Comment by sasanrose** [comment]
@drAlberT Done

**Pull request closed without merging**
